export enum ProposalModerationStatus { Active = 0, Invalidated = 1 }
export interface PageResult<T>{items:T[];pageNumber:number;pageSize:number;totalCount:number;totalPages:number;hasPreviousPage:boolean;hasNextPage:boolean}
export interface AdminProposalListItem{proposalId:string;jobPostId:string;jobPostTitle:string;clientId:string;clientName:string;clientAvatar:string|null;freelancerId:string;freelancerName:string;freelancerAvatar:string|null;proposedBudget:number|null;estimatedDuration:string|null;submittedAt:string|null;updatedAt:string|null;lifecycleStatus:number;moderationStatus:number;aiInterviewStatus:number|null;negotiationStatus:number|null;hasContract:boolean;contractId:string|null;contractStatus:number|null;hasReport:boolean;hasDispute:boolean;reportCount:number;disputeCount:number}
export interface AdminProposalParty{userId:string;name:string;avatar:string|null;summary:string|null;accountStatus:number;isActive:boolean;isFlagged:boolean;violationCount:number;reportCount:number;skills:string[];eloPoints:number|null;isPremium:boolean}
export interface AdminProposalWorkItem{workItemId:string;title:string;description:string|null;deliverables:string|null;estimatedDuration:string|null;order:number}
export interface AdminProposalMilestone{milestoneId:string;title:string;description:string|null;amount:number;estimatedDuration:string|null;dueDate:string|null;deliverables:string|null;acceptanceCriteria:string|null;order:number;workItems:AdminProposalWorkItem[]}
export interface AdminProposalQuestion{questionId:string;question:string;order:number;required:boolean;answer:string|null;answeredAt:string|null;timerStartedAt:string|null;timerCompletedAt:string|null;timerLocked:boolean|null}
export interface AdminProposalAi{definitionId:string|null;definitionStatus:number|null;attemptId:string|null;attemptStatus:number|null;startedAt:string|null;completedAt:string|null;score:number|null;compatibilityScore:number|null;result:string|null;recommendedHire:boolean|null;answers:{questionIndex:number;question:string|null;transcript:string|null;score:number|null}[];judgingScore:number|null;judgingSummary:string|null;judgedAt:string|null;reviewStartedAt:string|null;reviewCompletedAt:string|null;reviewLocked:boolean|null}
export interface AdminProposalOffer{offerId:string;conversationId:string;createdByUserId:string;createdByName:string;createdByAvatar:string|null;budget:number;startDate:string|null;endDate:string|null;scope:string|null;status:number;createdAt:string;respondedAt:string|null;milestones:{title:string;description:string|null;amount:number;estimatedDuration:string|null;dueDate:string|null;workItems:AdminProposalWorkItem[]}[]}
export interface AdminProposalRelation{id:string;kind:string;relation:string;status:number;reason:string|null;createdAt:string;contractId:string|null;relatedId:string|null}
export interface AdminProposalDetail{proposalId:string;coverLetter:string|null;proposedBudget:number|null;estimatedDuration:string|null;analysisSummary:string|null;solutionApproach:string|null;deliverables:string|null;assumptions:string|null;outOfScope:string|null;submittedAt:string|null;updatedAt:string|null;lifecycleStatus:number;moderationStatus:number;invalidationReason:string|null;invalidatedAt:string|null;invalidatedByAdminId:string|null;invalidatedByAdminName:string|null;jobPostId:string;jobPostTitle:string;jobPostDescription:string;jobBudgetMin:number|null;jobBudgetMax:number|null;jobDuration:string|null;jobStatus:number;jobVisibility:number|null;requiredSkills:string[];client:AdminProposalParty;freelancer:AdminProposalParty;answers:AdminProposalQuestion[];milestones:AdminProposalMilestone[];unassignedWorkItems:AdminProposalWorkItem[];aiInterview:AdminProposalAi|null;negotiationHistory:AdminProposalOffer[];contract:{contractId:string;title:string;status:number;budget:number;startDate:string|null;endDate:string|null;createdAt:string;milestoneCount:number;escrowFunded:number|null;escrowReleased:number|null;contractReportCount:number;disputeCount:number}|null;reports:AdminProposalRelation[];contractReports:AdminProposalRelation[];disputes:AdminProposalRelation[];internalNotes:{noteId:string;adminId:string;adminName:string;adminAvatar:string|null;content:string;createdAt:string}[];auditHistory:{auditId:string;adminId:string;adminName:string;adminAvatar:string|null;action:string;oldValues:string|null;newValues:string|null;correlationId:string;createdAt:string}[]}
export interface AdminProposalListParams{search?:string;lifecycleStatus?:number;moderationStatus?:number;clientId?:string;freelancerId?:string;jobPostId?:string;submittedFrom?:string;submittedTo?:string;updatedFrom?:string;updatedTo?:string;minBudget?:number;maxBudget?:number;hasContract?:boolean;contractStatus?:number;hasReport?:boolean;hasDispute?:boolean;aiInterviewStatus?:number;negotiationStatus?:number;sortBy?:string;sortDescending?:boolean;page?:number;pageSize?:number}
