import { useEffect, useState } from 'react';
import { Link } from 'react-router';
import { adminGetAPI } from '../../../api/adminAPI/GET';
import { UserProfileLink } from '../../../shared/components/UserProfileLink';
import type { AccountReportItem } from '../../../types/models/AdminPhase1';
import '../styles/admin-phase-one.css';
import { AppLayout } from '../../../shared/components/AppLayout';

export default function AdminAccountReportsScreen(){const [items,setItems]=useState<AccountReportItem[]>([]);const [search,setSearch]=useState('');const [status,setStatus]=useState('');const [type,setType]=useState('');const [accountStatus,setAccountStatus]=useState('');const [hasEvidence,setHasEvidence]=useState('');const [flagged,setFlagged]=useState('');const [page,setPage]=useState(1);const [pages,setPages]=useState(1);const [error,setError]=useState('');
 const load=async(nextPage=page)=>{const r=await adminGetAPI.getAccountReports({page:nextPage,pageSize:20,search:search||undefined,status:status===''?undefined:Number(status),type:type===''?undefined:Number(type),accountStatus:accountStatus===''?undefined:Number(accountStatus),hasEvidence:hasEvidence===''?undefined:hasEvidence==='true',isFlagged:flagged===''?undefined:flagged==='true'});if(r.success&&r.data){setItems(r.data.items);setPage(r.data.pageNumber);setPages(r.data.totalPages)}else setError(r.message||'Unable to load account reports.');};useEffect(()=>{void load(1);},[]);
 return <AppLayout><main className="admin-phase"><div className="admin-phase__header"><div><h1>Account Reports</h1><p>User-to-user safety reports and account enforcement.</p></div></div>{error&&<div className="admin-phase__error">{error}</div>}<section className="admin-phase__panel"><div className="admin-phase__filters"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search user or reason"/><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option><option value="0">Pending</option><option value="1">Reviewing</option><option value="2">Resolved</option><option value="3">Dismissed</option></select><select value={type} onChange={e=>setType(e.target.value)}><option value="">All report types</option>{[0,1,2,3,4,5].map(x=><option key={x} value={x}>Type {x}</option>)}</select><select value={accountStatus} onChange={e=>setAccountStatus(e.target.value)}><option value="">All account states</option><option value="0">Active</option><option value="1">Suspended</option><option value="2">Banned</option></select><select value={hasEvidence} onChange={e=>setHasEvidence(e.target.value)}><option value="">Any evidence</option><option value="true">Has evidence</option><option value="false">No evidence</option></select><select value={flagged} onChange={e=>setFlagged(e.target.value)}><option value="">Any flag state</option><option value="true">Flagged</option><option value="false">Not flagged</option></select><button className="primary" onClick={()=>load(1)}>Apply filters</button></div><table><thead><tr><th>Report</th><th>Reporter</th><th>Reported user</th><th>Account</th><th>Evidence</th><th>Created</th></tr></thead><tbody>{items.map(x=><tr key={x.id}><td><Link to={`/admin/reports/accounts/${x.id}`}>{x.reason}</Link><small>Status {x.status}</small></td><td><UserProfileLink userId={x.reporterId} role={x.reporterRole}>{x.reporterName}</UserProfileLink></td><td><UserProfileLink userId={x.reportedUserId} role={x.reportedUserRole}>{x.reportedUserName}</UserProfileLink> <Link to={`/admin/users?preview=${encodeURIComponent(x.reportedUserId)}`}>(manage)</Link><small>{x.violationCount} violations{x.isFlagged?' · flagged':''}</small></td><td>{['Active','Suspended','Banned'][x.accountStatus]}</td><td>{x.evidenceCount}</td><td>{new Date(x.createdAt).toLocaleString()}</td></tr>)}</tbody></table>{!items.length&&<p>No account reports match these filters.</p>}<div className="admin-phase__actions"><button disabled={page<=1} onClick={()=>load(page-1)}>Previous</button><span>Page {page} of {pages}</span><button disabled={page>=pages} onClick={()=>load(page+1)}>Next</button></div></section></main></AppLayout>}
