import { fireEvent, render, screen, waitFor } from '@testing-library/react';
import { MemoryRouter, Route, Routes } from 'react-router';
import { beforeEach, describe, expect, it, vi } from 'vitest';
import type { AdminContractReportDetail } from '../../../types/models/AdminContractReport';

const getApi=vi.hoisted(()=>({getContractReports:vi.fn(),getContractReportDetail:vi.fn(),getContractReportAttachmentDownload:vi.fn()}));
const postApi=vi.hoisted(()=>({assignContractReport:vi.fn(),requestContractReportInformation:vi.fn(),closeContractReport:vi.fn(),dismissContractReport:vi.fn(),addContractReportNote:vi.fn(),linkContractReportDispute:vi.fn(),escalateContractReport:vi.fn()}));
vi.mock('../../../api/adminAPI/GET',()=>({adminGetAPI:getApi}));vi.mock('../../../api/adminAPI/POST',()=>({adminPostAPI:postApi}));
import AdminContractReportsScreen from './AdminContractReportsScreen';
import AdminContractReportDetailScreen from './AdminContractReportDetailScreen';

const detail:AdminContractReportDetail={reportContractId:'report-1',issueType:2,description:'Delivery is late',desiredResolution:'Deliver the work',status:0,adminReviewStatus:1,createdAt:'2026-08-01T00:00:00Z',reporter:{userId:'client-1',name:'Client One',email:'c@test',role:'Client',accountStatus:0,violationCount:0,isFlagged:false},respondent:{userId:'free-1',name:'Freelancer One',email:'f@test',role:'Freelancer',accountStatus:0,violationCount:1,isFlagged:true},client:{userId:'client-1',name:'Client One',email:'c@test',role:'Client',accountStatus:0,violationCount:0,isFlagged:false},freelancer:{userId:'free-1',name:'Freelancer One',email:'f@test',role:'Freelancer',accountStatus:0,violationCount:1,isFlagged:true},contractId:'contract-1',contractTitle:'Website delivery',contractStatus:7,contractBudget:100,startDate:'2026-07-01',jobPostId:'job-1',jobPostTitle:'Build website',proposalId:'proposal-1',contractLocked:false,contractReportCount:1,disputeCount:0,milestone:{milestoneId:'mile-1',title:'Delivery',amount:100,status:2,releasedAmount:20,refundAmount:0,penaltyAmount:0},attachments:[{attachmentId:'attachment-1',fileName:'evidence.pdf',contentType:'application/pdf',fileSize:1000,uploadedAt:'2026-08-01T00:00:00Z',uploadedByName:'Client One',copiedToDispute:false}],escrowRequired:100,escrowFunded:100,escrowReleased:20,escrowRemaining:80,escrowTransactions:[],walletTransactions:[],messages:[{messageId:'message-1',conversationId:'conversation-1',senderUserId:'client-1',senderName:'Client One',messageType:0,content:'The delivery is late.',sentAt:'2026-08-01T00:00:00Z'}],internalNotes:[],informationRequests:[],auditHistory:[{auditId:'audit-1',adminId:'admin-1',adminName:'Admin',action:'ContractReportAssigned',newValues:'{"adminReviewStatus":1}',correlationId:'dd6da073-6d52-47ca-a0ef-e967445bde4a',createdAt:'2026-08-01T00:00:00Z'}],canAssign:true,canRequestInformation:true,canClose:true,canDismiss:true,canEscalate:true,canLinkDispute:true};

describe('Admin Contract Reports',()=>{beforeEach(()=>{vi.clearAllMocks();getApi.getContractReports.mockResolvedValue({success:true,data:{items:[{reportContractId:'report-1',contractId:'contract-1',contractTitle:'Website delivery',jobPostId:'job-1',jobPostTitle:'Build website',reporterId:'client-1',reporterName:'Client One',reporterRole:'Client',respondentId:'free-1',respondentName:'Freelancer One',respondentRole:'Freelancer',issueType:2,status:0,adminReviewStatus:1,createdAt:'2026-08-01T00:00:00Z',attachmentCount:1,escalationEligible:true}],pageNumber:1,totalPages:1,totalCount:1}});getApi.getContractReportDetail.mockResolvedValue({success:true,data:detail});});
 it('loads the server-paginated list and applies server filters',async()=>{render(<MemoryRouter><AdminContractReportsScreen/></MemoryRouter>);expect(await screen.findByText('Website delivery')).toBeInTheDocument();fireEvent.change(screen.getByPlaceholderText('Search contract, participant, or issue'),{target:{value:'late'}});fireEvent.click(screen.getByRole('button',{name:'Apply filters'}));await waitFor(()=>expect(getApi.getContractReports).toHaveBeenLastCalledWith(expect.objectContaining({search:'late',page:1})));});
 it('renders aggregate context and opens validated request-information dialog',async()=>{render(<MemoryRouter initialEntries={['/admin/reports/contracts/report-1']}><Routes><Route path="/admin/reports/contracts/:reportId" element={<AdminContractReportDetailScreen/>}/></Routes></MemoryRouter>);expect(await screen.findByText('Delivery is late')).toBeInTheDocument();expect(screen.getByText('Financial context (read-only)')).toBeInTheDocument();expect(screen.getByText((_,element)=>element?.tagName==='SUMMARY'&&Boolean(element.textContent?.includes('ContractReportAssigned')))).toBeInTheDocument();expect(screen.queryByText(/mock/i)).not.toBeInTheDocument();fireEvent.click(screen.getByRole('button',{name:'Request information'}));expect(screen.getByRole('dialog')).toBeInTheDocument();expect(screen.getByRole('button',{name:'Confirm'})).toBeDisabled();fireEvent.change(screen.getByPlaceholderText('Required message'),{target:{value:'Provide evidence'}});expect(screen.getByRole('button',{name:'Confirm'})).toBeEnabled();});
});
