import { useCallback, useEffect, useState } from 'react';
import { AlertTriangle, ArrowLeft, FileText, RefreshCw, StickyNote, X } from 'lucide-react';
import { useNavigate, useParams } from 'react-router';

import { adminGetAPI } from '../../../api/adminAPI/GET';
import { adminPatchAPI } from '../../../api/adminAPI/PATCH';
import { adminPostAPI } from '../../../api/adminAPI/POST';
import { AppLayout } from '../../../shared/components/AppLayout';
import { UserAvatar } from '../../../shared/components/UserAvatar';
import type { AdminProposalDetail } from '../../../types/models/AdminProposal';
import { aiAttemptLabels, aiDefinitionLabels, contractLabels, lifecycleLabels, moderationLabels, negotiationLabels, statusLabel, statusTone } from '../proposalStatus';
import '../styles/admin-phase-one.css';

type DetailTab = 'overview' | 'content' | 'answers' | 'milestones' | 'ai' | 'negotiation' | 'contract' | 'relations' | 'notes' | 'audit';
type DetailAction = 'invalidate' | 'restore' | 'note' | null;
const tabs: Array<{ id: DetailTab; label: string }> = [
  { id: 'overview', label: 'Overview' }, { id: 'content', label: 'Proposal Content' }, { id: 'answers', label: 'Answers' },
  { id: 'milestones', label: 'Milestones & Work Items' }, { id: 'ai', label: 'AI Interview' }, { id: 'negotiation', label: 'Negotiation' },
  { id: 'contract', label: 'Contract' }, { id: 'relations', label: 'Reports & Disputes' }, { id: 'notes', label: 'Internal Notes' }, { id: 'audit', label: 'Audit History' },
];
const reportLabels: Record<number, string> = { 0: 'Pending', 1: 'Reviewing', 2: 'Resolved', 3: 'Dismissed' };
const json = (value: string | null) => { if (!value) return '—'; try { return JSON.stringify(JSON.parse(value), null, 2); } catch { return value; } };

function Empty({ children }: { children: React.ReactNode }) { return <div className="admin-phase__state compact"><p>{children}</p></div>; }
function ReadOnlyCopy({ label, value }: { label: string; value: string | null | undefined }) { return <div className="admin-proposal-detail__copy"><h3>{label}</h3><p>{value || 'Not available'}</p></div>; }

export default function AdminProposalDetailScreen() {
  const { proposalId = '' } = useParams(); const navigate = useNavigate();
  const [data, setData] = useState<AdminProposalDetail | null>(null); const [tab, setTab] = useState<DetailTab>('overview');
  const [loading, setLoading] = useState(true); const [error, setError] = useState<{ message: string; status?: number } | null>(null);
  const [action, setAction] = useState<DetailAction>(null); const [reason, setReason] = useState(''); const [note, setNote] = useState(''); const [busy, setBusy] = useState(false); const [actionError, setActionError] = useState('');

  const load = useCallback(async () => {
    if (!proposalId) return;
    setLoading(true); setError(null);
    const response = await adminGetAPI.getProposalDetail(proposalId);
    if (response.success && response.data) setData(response.data);
    else { setData(null); setError({ message: response.message || 'Unable to load proposal.', status: response.statusCode }); }
    setLoading(false);
  }, [proposalId]);
  useEffect(() => { void load(); }, [load]);

  const apply = async () => {
    if (!action || !proposalId) return;
    setBusy(true); setActionError('');
    const response = action === 'note'
      ? await adminPostAPI.addProposalNote(proposalId, note.trim())
      : action === 'invalidate'
        ? await adminPatchAPI.invalidateProposal(proposalId, { reason: reason.trim(), internalNote: note.trim() || undefined })
        : await adminPatchAPI.restoreProposal(proposalId, { reason: reason.trim(), internalNote: note.trim() || undefined });
    if (response.success && response.data) { setData(response.data); setAction(null); setReason(''); setNote(''); }
    else setActionError(response.statusCode === 409 ? `Conflict: ${response.message}` : response.message || 'The action could not be completed.');
    setBusy(false);
  };

  if (loading) return <AppLayout><main className="admin-phase"><button onClick={() => navigate('/admin/proposals')}><ArrowLeft size={16} /> Proposals</button><section className="admin-phase__panel admin-phase__skeleton-list" role="status" aria-label="Loading proposal detail">{Array.from({ length: 7 }).map((_, index) => <div className="admin-phase__skeleton" key={index} />)}</section></main></AppLayout>;
  if (error || !data) { const heading = error?.status === 404 ? 'Proposal not found' : error?.status === 401 || error?.status === 403 ? 'Access denied' : 'Proposal could not be loaded'; return <AppLayout><main className="admin-phase"><button onClick={() => navigate('/admin/proposals')}><ArrowLeft size={16} /> Proposals</button><section className="admin-phase__panel admin-phase__state admin-phase__state--error" role="alert"><AlertTriangle size={32} /><h1>{heading}</h1><p>{error?.message || 'No proposal data is available.'}</p><button onClick={() => void load()}><RefreshCw size={16} /> Retry</button></section></main></AppLayout>; }

  const lifecycle = statusLabel(lifecycleLabels, data.lifecycleStatus); const moderation = statusLabel(moderationLabels, data.moderationStatus);
  const aiStatus = data.aiInterview?.attemptStatus !== null && data.aiInterview?.attemptStatus !== undefined ? statusLabel(aiAttemptLabels, data.aiInterview.attemptStatus) : statusLabel(aiDefinitionLabels, data.aiInterview?.definitionStatus);

  return <AppLayout><main className="admin-phase admin-proposal-detail">
    <header className="admin-phase__header"><div><button className="admin-phase__back" onClick={() => navigate('/admin/proposals')}><ArrowLeft size={16} /> Proposals</button><p className="admin-phase__eyebrow"><FileText size={16} /> Proposal #{data.proposalId.slice(0, 8)}</p><h1>{data.jobPostTitle}</h1><div className="admin-proposal-detail__status"><span className={`admin-phase__badge ${statusTone(lifecycle)}`}>{lifecycle}</span><span className={`admin-phase__badge ${statusTone(moderation)}`}>{moderation}</span></div></div><div className="admin-phase__actions"><button className={data.moderationStatus === 0 ? 'danger' : 'primary'} onClick={() => setAction(data.moderationStatus === 0 ? 'invalidate' : 'restore')}>{data.moderationStatus === 0 ? 'Invalidate' : 'Restore'}</button><button onClick={() => setAction('note')}><StickyNote size={16} /> Add internal note</button></div></header>
    {data.invalidationReason && <div className="admin-phase__notice"><strong>Latest invalidation:</strong> {data.invalidationReason} · {data.invalidatedByAdminName || 'Admin'}</div>}
    <nav className="admin-phase__tabs admin-proposal-detail__tabs" role="tablist" aria-label="Proposal detail sections">{tabs.map(item => <button key={item.id} role="tab" aria-selected={tab === item.id} className={tab === item.id ? 'active' : ''} onClick={() => setTab(item.id)}>{item.label}</button>)}</nav>

    {tab === 'overview' && <section className="admin-phase__grid" role="tabpanel"><article className="admin-phase__panel"><h2>Proposal Overview</h2><dl className="admin-proposal-detail__facts"><div><dt>Budget</dt><dd>{data.proposedBudget?.toLocaleString() ?? 'Not available'}</dd></div><div><dt>Duration</dt><dd>{data.estimatedDuration || 'Not available'}</dd></div><div><dt>Submitted</dt><dd>{data.submittedAt ? new Date(data.submittedAt).toLocaleString() : 'Draft'}</dd></div><div><dt>Updated</dt><dd>{data.updatedAt ? new Date(data.updatedAt).toLocaleString() : 'Not available'}</dd></div></dl><button className="admin-phase__link" onClick={() => navigate(`/admin/jobs?preview=${encodeURIComponent(data.jobPostId)}`)}>Open related Job Post</button></article><article className="admin-phase__panel"><h2>Parties</h2>{[data.client, data.freelancer].map(party => <button className="admin-proposal-detail__party" key={party.userId} onClick={() => navigate(`/admin/users?preview=${encodeURIComponent(party.userId)}`)}><UserAvatar name={party.name} src={party.avatar} size="lg" premium={party.isPremium} /><span><strong>{party.name}</strong><small>{party.userId === data.client.userId ? 'Client' : 'Freelancer'} · {party.reportCount} report(s) · {party.violationCount} violation(s)</small><small>{party.summary || 'No profile summary'}</small></span></button>)}</article></section>}
    {tab === 'content' && <section className="admin-phase__panel" role="tabpanel"><p className="admin-phase__readonly">Freelancer-authored content is read-only for administrators.</p><ReadOnlyCopy label="Cover Letter" value={data.coverLetter} /><ReadOnlyCopy label="Analysis Summary" value={data.analysisSummary} /><ReadOnlyCopy label="Solution Approach" value={data.solutionApproach} /><ReadOnlyCopy label="Deliverables" value={data.deliverables} /><ReadOnlyCopy label="Assumptions" value={data.assumptions} /><ReadOnlyCopy label="Out of Scope" value={data.outOfScope} /></section>}
    {tab === 'answers' && <section className="admin-phase__panel admin-proposal-detail__stack" role="tabpanel"><h2>Proposal Answers</h2>{data.answers.length ? data.answers.map(answer => <article key={answer.questionId}><h3>{answer.order + 1}. {answer.question}{answer.required ? ' *' : ''}</h3><p>{answer.answer || 'No answer provided.'}</p><small>{answer.answeredAt ? `Answered ${new Date(answer.answeredAt).toLocaleString()}` : 'Not answered'}{answer.timerStartedAt ? ` · Timer ${answer.timerLocked ? 'locked' : 'unlocked'}` : ''}</small></article>) : <Empty>No proposal questions or answers.</Empty>}</section>}
    {tab === 'milestones' && <section className="admin-phase__panel admin-proposal-detail__stack" role="tabpanel"><h2>Proposed Milestones & Work Items</h2>{data.milestones.length ? data.milestones.map(milestone => <article key={milestone.milestoneId}><h3>{milestone.order + 1}. {milestone.title} · {milestone.amount.toLocaleString()}</h3><p>{milestone.description || 'No description.'}</p>{milestone.acceptanceCriteria && <p><strong>Acceptance:</strong> {milestone.acceptanceCriteria}</p>}{milestone.workItems.length ? <ul>{milestone.workItems.map(item => <li key={item.workItemId}><strong>{item.title}</strong> — {item.deliverables || item.description || 'No detail'}</li>)}</ul> : <small>No work items.</small>}</article>) : <Empty>No proposed milestones.</Empty>}{data.unassignedWorkItems.length > 0 && <article><h3>Unassigned work items</h3><ul>{data.unassignedWorkItems.map(item => <li key={item.workItemId}>{item.title} — {item.deliverables || item.description || 'No detail'}</li>)}</ul></article>}</section>}
    {tab === 'ai' && <section className="admin-phase__panel" role="tabpanel"><h2>AI Interview</h2>{data.aiInterview ? <><div className="admin-proposal-detail__facts"><div><dt>Status</dt><dd><span className={`admin-phase__badge ${statusTone(aiStatus)}`}>{aiStatus}</span></dd></div><div><dt>Score</dt><dd>{data.aiInterview.score ?? data.aiInterview.judgingScore ?? 'Not available'}</dd></div><div><dt>Recommended hire</dt><dd>{data.aiInterview.recommendedHire === null ? 'Not available' : data.aiInterview.recommendedHire ? 'Yes' : 'No'}</dd></div></div><p>{data.aiInterview.result || data.aiInterview.judgingSummary || 'No evaluation summary.'}</p><div className="admin-proposal-detail__stack">{data.aiInterview.answers.map(answer => <details key={answer.questionIndex}><summary>Question {answer.questionIndex + 1} · score {answer.score ?? 'Not available'}</summary><p>{answer.question || 'Question text unavailable.'}</p><p>{answer.transcript || 'No transcript stored.'}</p></details>)}</div></> : <Empty>No AI interview data.</Empty>}</section>}
    {tab === 'negotiation' && <section className="admin-phase__panel admin-proposal-detail__stack" role="tabpanel"><h2>Negotiation History</h2>{data.negotiationHistory.length ? data.negotiationHistory.map(offer => { const offerStatus = statusLabel(negotiationLabels, offer.status); return <article key={offer.offerId}><header><UserAvatar name={offer.createdByName} src={offer.createdByAvatar} size="sm" /><div><strong>{offer.createdByName}</strong><small>{new Date(offer.createdAt).toLocaleString()}</small></div><span className={`admin-phase__badge ${statusTone(offerStatus)}`}>{offerStatus}</span></header><p><strong>{offer.budget.toLocaleString()}</strong> · {offer.scope || 'No scope summary'}</p>{offer.milestones.map((milestone, index) => <small key={`${offer.offerId}-${index}`}>{milestone.title}: {milestone.amount.toLocaleString()}</small>)}</article>; }) : <Empty>No negotiation offers.</Empty>}</section>}
    {tab === 'contract' && <section className="admin-phase__panel" role="tabpanel"><h2>Resulting Contract</h2>{data.contract ? <><dl className="admin-proposal-detail__facts"><div><dt>Title</dt><dd>{data.contract.title}</dd></div><div><dt>Status</dt><dd>{statusLabel(contractLabels, data.contract.status)}</dd></div><div><dt>Budget</dt><dd>{data.contract.budget.toLocaleString()}</dd></div><div><dt>Milestones</dt><dd>{data.contract.milestoneCount}</dd></div><div><dt>Escrow funded</dt><dd>{data.contract.escrowFunded ?? 'Not available'}</dd></div><div><dt>Escrow released</dt><dd>{data.contract.escrowReleased ?? 'Not available'}</dd></div></dl><button className="admin-phase__link" onClick={() => navigate(`/admin/contracts?contractId=${encodeURIComponent(data.contract!.contractId)}`)}>Open Contract Management</button></> : <Empty>No contract has been created.</Empty>}</section>}
    {tab === 'relations' && <section className="admin-phase__grid" role="tabpanel"><article className="admin-phase__panel"><h2>Reports</h2>{data.reports.map(report => <div className="admin-proposal-detail__relation" key={report.id}><strong>{report.kind}</strong><span className="admin-phase__badge">{statusLabel(reportLabels, report.status)}</span><p>{report.reason || 'No reason supplied.'}</p></div>)}{data.contractReports.map(report => <button className="admin-proposal-detail__relation" key={report.id} onClick={() => navigate(`/admin/reports/contracts/${report.id}`)}><strong>Contract Report</strong><span className="admin-phase__badge">{statusLabel(reportLabels, report.status)}</span><p>{report.reason || 'No reason supplied.'}</p></button>)}{!data.reports.length && !data.contractReports.length && <Empty>No related reports.</Empty>}</article><article className="admin-phase__panel"><h2>Disputes</h2>{data.disputes.map(dispute => <button className="admin-proposal-detail__relation" key={dispute.id} onClick={() => navigate(`/admin/disputes/${dispute.id}`)}><strong>Dispute</strong><span className="admin-phase__badge">{statusLabel({}, dispute.status)}</span><p>{dispute.reason || 'No reason supplied.'}</p></button>)}{!data.disputes.length && <Empty>No related disputes.</Empty>}</article></section>}
    {tab === 'notes' && <section className="admin-phase__panel admin-proposal-detail__stack" role="tabpanel"><h2>Internal Notes</h2>{data.internalNotes.length ? data.internalNotes.map(item => <article key={item.noteId}><header><UserAvatar name={item.adminName} src={item.adminAvatar} size="sm" /><div><strong>{item.adminName}</strong><small>{new Date(item.createdAt).toLocaleString()}</small></div></header><p>{item.content}</p></article>) : <Empty>No internal notes.</Empty>}</section>}
    {tab === 'audit' && <section className="admin-phase__panel admin-proposal-detail__stack" role="tabpanel"><h2>Audit History</h2>{data.auditHistory.length ? data.auditHistory.map(item => <details key={item.auditId}><summary><UserAvatar name={item.adminName} src={item.adminAvatar} size="sm" /><span><strong>{item.action}</strong><small>{item.adminName} · {new Date(item.createdAt).toLocaleString()}</small></span></summary><pre>OLD {json(item.oldValues)}{`\n`}NEW {json(item.newValues)}</pre><small>Correlation {item.correlationId}</small></details>) : <Empty>No moderation audit events.</Empty>}</section>}

    {action && <div className="admin-phase__modal" role="alertdialog" aria-modal="true" aria-labelledby="proposal-detail-action-title"><div className="admin-phase__panel"><header><h2 id="proposal-detail-action-title">{action === 'note' ? 'Add internal note' : action === 'restore' ? 'Restore proposal' : 'Invalidate proposal'}</h2><button aria-label="Close action dialog" onClick={() => setAction(null)}><X size={18} /></button></header>{action !== 'note' && <textarea autoFocus aria-label="Moderation reason" placeholder="Required reason" value={reason} onChange={event => setReason(event.target.value)} />}<textarea autoFocus={action === 'note'} aria-label="Internal note" placeholder={action === 'note' ? 'Required private note' : 'Optional private note'} value={note} onChange={event => setNote(event.target.value)} />{actionError && <p className="admin-phase__error" role="alert">{actionError}</p>}<div className="admin-phase__actions"><button onClick={() => { setAction(null); setActionError(''); }}>Cancel</button><button disabled={busy || (action === 'note' ? !note.trim() : !reason.trim())} className={action === 'invalidate' ? 'danger' : 'primary'} onClick={() => void apply()}>{busy ? 'Working…' : 'Confirm'}</button></div></div></div>}
  </main></AppLayout>;
}
