import { useCallback, useEffect, useState } from 'react';
import { useNavigate, useParams } from 'react-router';
import { adminGetAPI } from '../../../api/adminAPI/GET';
import { adminPatchAPI } from '../../../api/adminAPI/PATCH';
import { adminPostAPI } from '../../../api/adminAPI/POST';
import type { AdminProposalDetail } from '../../../types/models/AdminProposal';
import '../styles/admin-phase-one.css';
const lifecycle=['Draft','Pending','Shortlisted','Accepted','Rejected','Withdrawn']; const moderation=['Active','Invalidated']; const json=(v:string|null)=>{try{return v?JSON.stringify(JSON.parse(v),null,2):'—'}catch{return v||'—'}};
export default function AdminProposalDetailScreen(){const {proposalId}=useParams();const nav=useNavigate();const [data,setData]=useState<AdminProposalDetail|null>(null);const [error,setError]=useState('');const [action,setAction]=useState<'invalidate'|'restore'|'note'|null>(null);const [reason,setReason]=useState('');const [note,setNote]=useState('');const [busy,setBusy]=useState(false);const load=useCallback(async()=>{if(!proposalId)return;try{const r=await adminGetAPI.getProposalDetail(proposalId);if(!r.success||!r.data)throw new Error(r.message);setData(r.data)}catch(e){setError(e instanceof Error?e.message:'Unable to load proposal')}},[proposalId]);useEffect(()=>{void load()},[load]);const apply=async()=>{if(!proposalId||!action)return;setBusy(true);try{const r=action==='note'?await adminPostAPI.addProposalNote(proposalId,note.trim()):action==='invalidate'?await adminPatchAPI.invalidateProposal(proposalId,{reason:reason.trim(),internalNote:note.trim()||undefined}):await adminPatchAPI.restoreProposal(proposalId,{reason:reason.trim(),internalNote:note.trim()||undefined});if(!r.success||!r.data)throw new Error(r.message);setData(r.data);setAction(null);setReason('');setNote('')}catch(e){setError(e instanceof Error?e.message:'Action failed')}finally{setBusy(false)}};if(!data)return <main className="admin-phase"><button onClick={()=>nav('/admin/proposals')}>Back</button><p>{error||'Loading proposal…'}</p></main>;return <main className="admin-phase"><header><button onClick={()=>nav('/admin/proposals')}>← Proposals</button><p className="admin-phase__eyebrow">Proposal {data.proposalId}</p><h1>{data.jobPostTitle}</h1><div className="admin-phase__actions"><span className="admin-phase__badge">{lifecycle[data.lifecycleStatus]}</span><span className={`admin-phase__badge ${data.moderationStatus?'danger':'success'}`}>{moderation[data.moderationStatus]}</span><button className={data.moderationStatus?'primary':'danger'} onClick={()=>setAction(data.moderationStatus?'restore':'invalidate')}>{data.moderationStatus?'Restore':'Invalidate'}</button><button onClick={()=>setAction('note')}>Add internal note</button></div>{data.invalidationReason&&<p>Latest invalidation: {data.invalidationReason} · {data.invalidatedByAdminName||'Admin'}</p>}</header>{error&&<p className="admin-phase__error">{error}</p>}
 <section className="admin-phase__grid"><article className="admin-phase__panel"><h2>Proposal overview</h2><dl><dt>Budget</dt><dd>{data.proposedBudget?.toLocaleString()??'—'}</dd><dt>Duration</dt><dd>{data.estimatedDuration||'—'}</dd><dt>Submitted</dt><dd>{data.submittedAt?new Date(data.submittedAt).toLocaleString():'Draft'}</dd></dl><h3>Cover letter</h3><p className="whitespace-pre-wrap">{data.coverLetter||'—'}</p><h3>Approach</h3><p>{data.analysisSummary||data.solutionApproach||'—'}</p></article><article className="admin-phase__panel"><h2>Job Post context</h2><button className="admin-phase__link" onClick={()=>nav(`/admin/jobs/${data.jobPostId}`)}>{data.jobPostTitle}</button><p>{data.jobPostDescription}</p><p>{data.requiredSkills.join(' · ')||'No required skills'}</p><h3>Parties</h3><button className="admin-phase__link" onClick={()=>nav(`/admin/users/${data.client.userId}`)}>Client: {data.client.name}</button><small>{data.client.summary} · {data.client.reportCount} reports · {data.client.violationCount} violations</small><button className="admin-phase__link" onClick={()=>nav(`/admin/users/${data.freelancer.userId}`)}>Freelancer: {data.freelancer.name}</button><small>{data.freelancer.summary} · Elo {data.freelancer.eloPoints??'—'} · {data.freelancer.skills.join(', ')}</small></article></section>
 <section className="admin-phase__panel"><h2>Answers and integrity timers</h2>{data.answers.map(x=><article key={x.questionId}><strong>{x.order+1}. {x.question}</strong><p>{x.answer||'No answer'}</p><small>{x.timerStartedAt?`Timer ${new Date(x.timerStartedAt).toLocaleString()} · locked ${String(x.timerLocked)}`:'No timer'}</small></article>)}</section>
 <section className="admin-phase__panel"><h2>Proposed milestones and work items</h2>{data.milestones.map(m=><article key={m.milestoneId}><h3>{m.order+1}. {m.title} · {m.amount.toLocaleString()}</h3><p>{m.description} {m.acceptanceCriteria&&`Acceptance: ${m.acceptanceCriteria}`}</p>{m.workItems.map(w=><p key={w.workItemId}>• {w.title} — {w.deliverables||w.description}</p>)}</article>)}{!data.milestones.length&&<p>No proposed milestones.</p>}</section>
 <section className="admin-phase__grid"><article className="admin-phase__panel"><h2>AI Interview (read-only)</h2>{data.aiInterview?<><p>Status {data.aiInterview.attemptStatus??data.aiInterview.definitionStatus} · Score {data.aiInterview.score??data.aiInterview.judgingScore??'—'}</p><p>{data.aiInterview.result||data.aiInterview.judgingSummary}</p>{data.aiInterview.answers.map(x=><details key={x.questionIndex}><summary>Question {x.questionIndex+1} · score {x.score??'—'}</summary><p>{x.question}</p><p>{x.transcript||'No transcript stored'}</p></details>)}</>:<p>No AI interview data.</p>}</article><article className="admin-phase__panel"><h2>Resulting Contract</h2>{data.contract?<><button className="admin-phase__link" onClick={()=>nav(`/admin/contracts/${data.contract!.contractId}`)}>{data.contract.title}</button><p>Status {data.contract.status} · Budget {data.contract.budget.toLocaleString()}</p><p>Escrow {data.contract.escrowFunded??0} funded / {data.contract.escrowReleased??0} released</p></>:<p>No contract has been created.</p>}</article></section>
 <section className="admin-phase__panel"><h2>Negotiation history (read-only)</h2>{data.negotiationHistory.map(x=><article key={x.offerId}><strong>{new Date(x.createdAt).toLocaleString()} · {x.createdByName} · status {x.status}</strong><p>{x.budget.toLocaleString()} · {x.scope}</p>{x.milestones.map((m,i)=><small key={i}>{m.title}: {m.amount.toLocaleString()}</small>)}</article>)}{!data.negotiationHistory.length&&<p>No negotiation offers.</p>}</section>
 <section className="admin-phase__grid"><article className="admin-phase__panel"><h2>Reports</h2>{data.reports.map(x=><p key={x.id}>{x.kind} · {x.relation} · status {x.status}<br/>{x.reason}</p>)}{data.contractReports.map(x=><button className="admin-phase__link" key={x.id} onClick={()=>nav(`/admin/reports/contracts/${x.id}`)}>Contract Report · {x.reason}</button>)}{!data.reports.length&&!data.contractReports.length&&<p>No related reports.</p>}</article><article className="admin-phase__panel"><h2>Disputes</h2>{data.disputes.map(x=><button className="admin-phase__link" key={x.id} onClick={()=>nav(`/admin/disputes/${x.id}`)}>Dispute · status {x.status} · {x.reason}</button>)}{!data.disputes.length&&<p>No related disputes.</p>}</article></section>
 <section className="admin-phase__grid"><article className="admin-phase__panel"><h2>Internal notes</h2>{data.internalNotes.map(x=><p key={x.noteId}><strong>{x.adminName}</strong> <small>{new Date(x.createdAt).toLocaleString()}</small><br/>{x.content}</p>)}{!data.internalNotes.length&&<p>No notes.</p>}</article><article className="admin-phase__panel"><h2>Real Audit history</h2>{data.auditHistory.map(x=><details key={x.auditId}><summary>{new Date(x.createdAt).toLocaleString()} · {x.adminName} · {x.action}</summary><pre>OLD {json(x.oldValues)}{`\n`}NEW {json(x.newValues)}</pre><small>Correlation {x.correlationId}</small></details>)}{!data.auditHistory.length&&<p>No moderation audit events.</p>}</article></section>
 {action&&<div className="admin-phase__modal" role="dialog" aria-modal="true"><div className="admin-phase__panel"><h2>{action==='note'?'Add internal note':action==='restore'?'Restore proposal':'Invalidate proposal'}</h2>{action!=='note'&&<textarea placeholder="Required reason" value={reason} onChange={e=>setReason(e.target.value)}/>}<textarea placeholder={action==='note'?'Required private note':'Optional private note'} value={note} onChange={e=>setNote(e.target.value)}/><div className="admin-phase__actions"><button onClick={()=>setAction(null)}>Cancel</button><button disabled={busy||(action==='note'?!note.trim():!reason.trim())} className={action==='invalidate'?'danger':'primary'} onClick={()=>void apply()}>Confirm</button></div></div></div>}</main>}
