import { useCallback, useEffect, useState } from 'react';
import { useNavigate } from 'react-router';
import { adminGetAPI } from '../../../api/adminAPI/GET';
import { adminPatchAPI } from '../../../api/adminAPI/PATCH';
import type { AdminProposalListItem } from '../../../types/models/AdminProposal';
import { ProposalModerationStatus } from '../../../types/models/AdminProposal';
import '../styles/admin-phase-one.css';

const lifecycle = ['Draft','Pending','Shortlisted','Accepted','Rejected','Withdrawn'];
const moderation = ['Active','Invalidated'];
const date = (v:string|null) => v ? new Date(v).toLocaleString() : 'Draft';

export default function AdminProposalsScreen(){
 const nav=useNavigate(); const [items,setItems]=useState<AdminProposalListItem[]>([]); const [page,setPage]=useState(1); const [pages,setPages]=useState(1); const [total,setTotal]=useState(0); const [search,setSearch]=useState(''); const [status,setStatus]=useState(''); const [mod,setMod]=useState(''); const [relation,setRelation]=useState(''); const [sort,setSort]=useState('submittedAt'); const [clientId,setClientId]=useState(''); const [freelancerId,setFreelancerId]=useState(''); const [jobPostId,setJobPostId]=useState(''); const [submittedFrom,setSubmittedFrom]=useState(''); const [submittedTo,setSubmittedTo]=useState(''); const [updatedFrom,setUpdatedFrom]=useState(''); const [updatedTo,setUpdatedTo]=useState(''); const [minBudget,setMinBudget]=useState(''); const [maxBudget,setMaxBudget]=useState(''); const [aiStatus,setAiStatus]=useState(''); const [negotiationStatus,setNegotiationStatus]=useState(''); const [contractStatus,setContractStatus]=useState(''); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [action,setAction]=useState<AdminProposalListItem|null>(null); const [reason,setReason]=useState(''); const [busy,setBusy]=useState(false);
 const load=useCallback(async()=>{setLoading(true);setError('');try{const r=await adminGetAPI.getProposals({page,pageSize:20,search:search||undefined,lifecycleStatus:status===''?undefined:Number(status),moderationStatus:mod===''?undefined:Number(mod),clientId:clientId||undefined,freelancerId:freelancerId||undefined,jobPostId:jobPostId||undefined,submittedFrom:submittedFrom?new Date(`${submittedFrom}T00:00:00Z`).toISOString():undefined,submittedTo:submittedTo?new Date(`${submittedTo}T23:59:59Z`).toISOString():undefined,updatedFrom:updatedFrom?new Date(`${updatedFrom}T00:00:00Z`).toISOString():undefined,updatedTo:updatedTo?new Date(`${updatedTo}T23:59:59Z`).toISOString():undefined,minBudget:minBudget?Number(minBudget):undefined,maxBudget:maxBudget?Number(maxBudget):undefined,aiInterviewStatus:aiStatus===''?undefined:Number(aiStatus),negotiationStatus:negotiationStatus===''?undefined:Number(negotiationStatus),contractStatus:contractStatus===''?undefined:Number(contractStatus),hasContract:relation==='contract'?true:relation==='no-contract'?false:undefined,hasReport:relation==='report'?true:undefined,hasDispute:relation==='dispute'?true:undefined,sortBy:sort,sortDescending:true});if(!r.success||!r.data)throw new Error(r.message||'Unable to load proposals');setItems(r.data.items);setPages(Math.max(1,r.data.totalPages));setTotal(r.data.totalCount)}catch(e){setError(e instanceof Error?e.message:'Unable to load proposals')}finally{setLoading(false)}},[page,search,status,mod,relation,sort,clientId,freelancerId,jobPostId,submittedFrom,submittedTo,updatedFrom,updatedTo,minBudget,maxBudget,aiStatus,negotiationStatus,contractStatus]); useEffect(()=>{void load()},[load]);
 const apply=async()=>{if(!action||!reason.trim())return;setBusy(true);try{const fn=action.moderationStatus===ProposalModerationStatus.Active?adminPatchAPI.invalidateProposal:adminPatchAPI.restoreProposal;const r=await fn(action.proposalId,{reason:reason.trim()});if(!r.success)throw new Error(r.message);setAction(null);setReason('');await load()}catch(e){setError(e instanceof Error?e.message:'Moderation failed')}finally{setBusy(false)}};
 return <main className="admin-phase"><header><p className="admin-phase__eyebrow">Content management</p><h1>Proposal management</h1><p>Read-only lifecycle oversight with independent, audited moderation.</p></header>
 <section className="admin-phase__panel admin-phase__filters"><input aria-label="Search proposals" placeholder="Proposal ID, job, client or freelancer" value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}}/><select aria-label="Lifecycle status" value={status} onChange={e=>{setStatus(e.target.value);setPage(1)}}><option value="">All lifecycle states</option>{lifecycle.map((x,i)=><option value={i} key={x}>{x}</option>)}</select><select aria-label="Moderation status" value={mod} onChange={e=>{setMod(e.target.value);setPage(1)}}><option value="">All moderation states</option>{moderation.map((x,i)=><option value={i} key={x}>{x}</option>)}</select><select aria-label="Relationship filter" value={relation} onChange={e=>{setRelation(e.target.value);setPage(1)}}><option value="">All relationships</option><option value="contract">Has contract</option><option value="no-contract">Has no contract</option><option value="report">Has report</option><option value="dispute">Has dispute</option></select><input aria-label="Client ID" placeholder="Client ID" value={clientId} onChange={e=>setClientId(e.target.value)}/><input aria-label="Freelancer ID" placeholder="Freelancer ID" value={freelancerId} onChange={e=>setFreelancerId(e.target.value)}/><input aria-label="Job Post ID" placeholder="Job Post ID" value={jobPostId} onChange={e=>setJobPostId(e.target.value)}/><label>Submitted from<input type="date" value={submittedFrom} onChange={e=>setSubmittedFrom(e.target.value)}/></label><label>Submitted to<input type="date" value={submittedTo} onChange={e=>setSubmittedTo(e.target.value)}/></label><label>Updated from<input type="date" value={updatedFrom} onChange={e=>setUpdatedFrom(e.target.value)}/></label><label>Updated to<input type="date" value={updatedTo} onChange={e=>setUpdatedTo(e.target.value)}/></label><input aria-label="Minimum budget" type="number" min="0" placeholder="Min budget" value={minBudget} onChange={e=>setMinBudget(e.target.value)}/><input aria-label="Maximum budget" type="number" min="0" placeholder="Max budget" value={maxBudget} onChange={e=>setMaxBudget(e.target.value)}/><input aria-label="AI Interview status" type="number" placeholder="AI status" value={aiStatus} onChange={e=>setAiStatus(e.target.value)}/><input aria-label="Negotiation status" type="number" placeholder="Offer status" value={negotiationStatus} onChange={e=>setNegotiationStatus(e.target.value)}/><input aria-label="Contract status" type="number" placeholder="Contract status" value={contractStatus} onChange={e=>setContractStatus(e.target.value)}/><select aria-label="Sort proposals" value={sort} onChange={e=>setSort(e.target.value)}><option value="submittedAt">Submitted</option><option value="updatedAt">Updated</option><option value="proposedBudget">Budget</option><option value="lifecycleStatus">Lifecycle</option><option value="moderationStatus">Moderation</option></select></section>
 {error&&<p className="admin-phase__error" role="alert">{error}</p>}{loading?<p>Loading proposals…</p>:<section className="admin-phase__panel"><div className="admin-phase__table-wrap"><table><thead><tr><th>Proposal / Job</th><th>Client</th><th>Freelancer</th><th>Budget</th><th>Submitted</th><th>Lifecycle</th><th>Moderation</th><th>AI / Negotiation</th><th>Contract</th><th>Reports</th><th>Actions</th></tr></thead><tbody>{items.map(x=><tr key={x.proposalId}><td><button className="admin-phase__link" onClick={()=>nav(`/admin/proposals/${x.proposalId}`)}>{x.proposalId.slice(0,8)}</button><small>{x.jobPostTitle}</small></td><td><button className="admin-phase__link" onClick={()=>nav(`/admin/users/${x.clientId}`)}>{x.clientName}</button></td><td><button className="admin-phase__link" onClick={()=>nav(`/admin/users/${x.freelancerId}`)}>{x.freelancerName}</button></td><td>{x.proposedBudget?.toLocaleString()??'—'}</td><td>{date(x.submittedAt)}</td><td><span className="admin-phase__badge">{lifecycle[x.lifecycleStatus]??x.lifecycleStatus}</span></td><td><span className={`admin-phase__badge ${x.moderationStatus?'danger':'success'}`}>{moderation[x.moderationStatus]}</span></td><td>AI {x.aiInterviewStatus??'—'}<small>Offer {x.negotiationStatus??'—'}</small></td><td>{x.hasContract?<button className="admin-phase__link" onClick={()=>nav(`/admin/contracts/${x.contractId}`)}>#{x.contractStatus}</button>:'No'}</td><td>{x.reportCount} / {x.disputeCount}</td><td><button onClick={()=>nav(`/admin/proposals/${x.proposalId}`)}>View</button><button className={x.moderationStatus?'':'danger'} onClick={()=>setAction(x)}>{x.moderationStatus?'Restore':'Invalidate'}</button></td></tr>)}</tbody></table></div>{!items.length&&<p>No proposals match these server-side filters.</p>}<footer className="admin-phase__pagination"><button disabled={page<=1} onClick={()=>setPage(p=>p-1)}>Previous</button><span>Page {page} of {pages} · {total} proposals</span><button disabled={page>=pages} onClick={()=>setPage(p=>p+1)}>Next</button></footer></section>}
 {action&&<div className="admin-phase__modal" role="dialog" aria-modal="true"><div className="admin-phase__panel"><h2>{action.moderationStatus?'Restore':'Invalidate'} proposal</h2><p>The lifecycle state and all authored, interview, negotiation, and contract history remain unchanged.</p><textarea autoFocus placeholder="Required reason" value={reason} onChange={e=>setReason(e.target.value)}/><div className="admin-phase__actions"><button onClick={()=>{setAction(null);setReason('')}}>Cancel</button><button className={action.moderationStatus?'primary':'danger'} disabled={busy||!reason.trim()} onClick={()=>void apply()}>Confirm</button></div></div></div>}
 </main>
}
