import { useEffect, useState } from 'react';
import { Link, useParams } from 'react-router';
import { adminGetAPI } from '../../../api/adminAPI/GET';
import { adminPutAPI } from '../../../api/adminAPI/PUT';
import { AccountReportResolutionAction, UserViolationType, type AccountReportDetail } from '../../../types/models/AdminPhase1';
import '../styles/admin-phase-one.css';
import { AppLayout } from '../../../shared/components/AppLayout';

export default function AdminAccountReportDetailScreen(){const {reportId=''}=useParams();const [data,setData]=useState<AccountReportDetail>();const [error,setError]=useState('');const load=async()=>{const r=await adminGetAPI.getAccountReportDetail(reportId);if(r.success&&r.data)setData(r.data);else setError(r.message||'Unable to load report.');};useEffect(()=>{void load();},[reportId]);
 const reviewing=async()=>{const r=await adminPutAPI.updateAccountReportStatus(reportId,1);if(!r.success)setError(r.message||'Update failed.');else setData(r.data);};
 const resolve=async(action:AccountReportResolutionAction)=>{const reason=window.prompt('Resolution reason')?.trim();if(!reason)return;let suspendedUntil:string|undefined;if(action===AccountReportResolutionAction.Suspension){const raw=window.prompt('Suspension end (UTC ISO date/time)');if(!raw)return;suspendedUntil=new Date(raw).toISOString();}const r=await adminPutAPI.resolveAccountReport(reportId,{action,reason,violationType:action===0?undefined:UserViolationType.PlatformPolicyViolation,suspendedUntil});if(!r.success)setError(r.message||'Resolution failed.');else setData(r.data);};
 const download=async(id:string)=>{const r=await adminGetAPI.getAccountReportEvidenceDownload(reportId,id);if(r.success&&r.data)window.open(r.data.downloadUrl,'_blank','noopener,noreferrer');else setError(r.message||'Download failed.');};
 if(!data)return <AppLayout><main className="admin-phase">{error?<div className="admin-phase__error">{error}</div>:<p>Loading report…</p>}</main></AppLayout>;const final=data.report.status>=2;
 return <AppLayout><main className="admin-phase"><div className="admin-phase__header"><div><Link to="/admin/reports/accounts">← Account Reports</Link><h1>{data.report.reason}</h1><p>{data.description}</p></div><span className="admin-phase__badge">Status {data.report.status}</span></div>{error&&<div className="admin-phase__error">{error}</div>}<section className="admin-phase__panel admin-phase__grid"><div className="admin-phase__stat"><small>Reporter</small>{data.report.reporterName}</div><div className="admin-phase__stat"><small>Reported user</small><Link to={`/admin/users?preview=${encodeURIComponent(data.report.reportedUserId)}`}>{data.report.reportedUserName}</Link></div><div className="admin-phase__stat"><small>Enforcement</small>{['Active','Suspended','Banned'][data.report.accountStatus]} · {data.report.violationCount} violations</div><div className="admin-phase__stat"><small>Assigned admin</small>{data.report.assignedAdminName||'Unassigned'}</div></section>
 <section className="admin-phase__panel"><h2>Evidence</h2>{data.evidence.map(x=><p key={x.id}><button onClick={()=>download(x.id)}>Download {x.fileName}</button> <small>{Math.ceil(x.fileSize/1024)} KB · {x.contentType}</small></p>)}{!data.evidence.length&&<p>No evidence supplied.</p>}</section>
 <section className="admin-phase__panel"><h2>Resolution</h2>{final?<p>This report is finalized and read-only. {data.adminNote}</p>:<div className="admin-phase__actions"><button onClick={reviewing}>Mark reviewing</button><button onClick={()=>resolve(AccountReportResolutionAction.None)}>Resolve without action</button><button onClick={()=>resolve(AccountReportResolutionAction.Warning)}>Warn</button><button onClick={()=>resolve(AccountReportResolutionAction.Suspension)}>Suspend</button><button className="danger" onClick={()=>resolve(AccountReportResolutionAction.PermanentBan)}>Permanently ban</button><button onClick={()=>adminPutAPI.updateAccountReportStatus(reportId,3).then(load)}>Dismiss</button></div>}</section>
 <section className="admin-phase__panel"><h2>History</h2><p>{data.previousReports.length} previous reports · {data.violations.length} violations</p>{data.auditLogs.map(x=><div key={x.id}><strong>{x.action}</strong><small>{new Date(x.createdAt).toLocaleString()}</small><pre>{typeof x.newValues==='string'?x.newValues:JSON.stringify(x.newValues,null,2)}</pre></div>)}</section></main></AppLayout>}
