import type { User, FreelancerProfile, ClientProfile } from '../../types/models/User';
import type { Job, Proposal, Review } from '../types/legacy';
import type { Project } from '../../types/models/Project';
import type { Message, Notification } from '../../types/models/Message';
import { UserRole } from '../../types/models/User';
import { FreelancerProfile as FreelancerProfileType, ClientProfile as ClientProfileType, ExperienceLevel, Availability, CompanySize } from '../../types/models/Profile';

// ─── Demo Users for Quick Login ───────────────────────────────────────
export const DEMO_USERS: User[] = [
  {
    id: 'demo_client_001',
    email: 'client@gigbridge.com',
    first_name: 'Demo',
    last_name: 'Client',
    full_name: 'Demo Client',
    phone_number: null,
    role: UserRole.Client,
    is_email_verified: true,
    is_active: true,
    preferred_language: 'en',
    last_login_at: null,
    login_failed_time: null,
    access_failed_count: 0,
    gigcoin_balance: 500,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'demo_freelancer_001',
    email: 'freelancer@gigbridge.com',
    first_name: 'Demo',
    last_name: 'Freelancer',
    full_name: 'Demo Freelancer',
    phone_number: null,
    role: UserRole.Freelancer,
    is_email_verified: true,
    is_active: true,
    preferred_language: 'en',
    last_login_at: null,
    login_failed_time: null,
    access_failed_count: 0,
    gigcoin_balance: 250,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'demo_admin_001',
    email: 'admin@gigbridge.com',
    first_name: 'Demo',
    last_name: 'Admin',
    full_name: 'Demo Admin',
    phone_number: null,
    role: UserRole.Admin,
    is_email_verified: true,
    is_active: true,
    preferred_language: 'en',
    last_login_at: null,
    login_failed_time: null,
    access_failed_count: 0,
    gigcoin_balance: 1000,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
];

// ─── Users ───────────────────────────────────────
export const SEED_USERS: User[] = [
  {
    id: 'u_client_1',
    email: 'jordan@techcorp.io',
    first_name: 'Jordan',
    last_name: 'Mitchell',
    full_name: 'Jordan Mitchell',
    phone_number: null,
    role: UserRole.Client,
    is_email_verified: true,
    is_active: true,
    preferred_language: 'en',
    last_login_at: '2024-04-15T10:30:00Z',
    login_failed_time: null,
    access_failed_count: 0,
    gigcoin_balance: 1000,
    created_at: '2024-01-15T00:00:00Z',
    updated_at: '2024-04-15T10:30:00Z',
  },
  {
    id: 'u_client_2',
    email: 'anika@startupxyz.com',
    first_name: 'Anika',
    last_name: 'Sharma',
    full_name: 'Anika Sharma',
    phone_number: null,
    role: UserRole.Client,
    is_email_verified: true,
    is_active: true,
    preferred_language: 'en',
    last_login_at: '2024-04-16T14:20:00Z',
    login_failed_time: null,
    access_failed_count: 0,
    gigcoin_balance: 750,
    created_at: '2024-03-08T00:00:00Z',
    updated_at: '2024-04-16T14:20:00Z',
  },
  {
    id: 'u_freelancer_1',
    email: 'alex@dev.pro',
    first_name: 'Alex',
    last_name: 'Johnson',
    full_name: 'Alex Johnson',
    phone_number: '+1-555-0101',
    role: UserRole.Freelancer,
    is_email_verified: true,
    is_active: true,
    preferred_language: 'en',
    last_login_at: '2024-04-17T08:15:00Z',
    login_failed_time: null,
    access_failed_count: 0,
    gigcoin_balance: 150,
    created_at: '2023-11-20T00:00:00Z',
    updated_at: '2024-04-17T08:15:00Z',
  },
  {
    id: 'u_freelancer_2',
    email: 'sarah@design.studio',
    first_name: 'Sarah',
    last_name: 'Chen',
    full_name: 'Sarah Chen',
    phone_number: '+1-555-0102',
    role: UserRole.Freelancer,
    is_email_verified: true,
    is_active: true,
    preferred_language: 'en',
    last_login_at: '2024-04-16T16:45:00Z',
    login_failed_time: null,
    access_failed_count: 0,
    gigcoin_balance: 300,
    created_at: '2023-09-05T00:00:00Z',
    updated_at: '2024-04-16T16:45:00Z',
  },
  {
    id: 'u_freelancer_3',
    email: 'marcus@data.science',
    first_name: 'Marcus',
    last_name: 'Rivera',
    full_name: 'Marcus Rivera',
    phone_number: null,
    role: UserRole.Freelancer,
    is_email_verified: false,
    is_active: true,
    preferred_language: 'en',
    last_login_at: '2024-04-14T12:00:00Z',
    login_failed_time: null,
    access_failed_count: 0,
    gigcoin_balance: 50,
    created_at: '2024-02-14T00:00:00Z',
    updated_at: '2024-04-14T12:00:00Z',
  },
  {
    id: 'u_admin_1',
    email: 'admin@gigbridge.ai',
    first_name: 'GigBridge',
    last_name: 'Admin',
    full_name: 'GigBridge Admin',
    phone_number: null,
    role: UserRole.Admin,
    is_email_verified: true,
    is_active: true,
    preferred_language: 'en',
    last_login_at: '2024-04-17T09:00:00Z',
    login_failed_time: null,
    access_failed_count: 0,
    gigcoin_balance: 5000,
    created_at: '2023-01-01T00:00:00Z',
    updated_at: '2024-04-17T09:00:00Z',
  },
];

export const SEED_FREELANCER_PROFILES: FreelancerProfileType[] = [
  {
    id: 'fp_1',
    user_id: 'demo_freelancer_001',
    title: 'Full-Stack Developer',
    bio: 'Experienced developer with 5+ years building modern web applications',
    hourly_rate: 75,
    experience_level: ExperienceLevel.Expert,
    availability: Availability.Available,
    location: 'San Francisco, CA',
    profile_completion_score: 95,
    rating: 4.8,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-04-17T00:00:00Z',
  },
  {
    id: 'fp_2',
    user_id: 'u_freelancer_1',
    title: 'Senior Full-Stack React Developer',
    bio: 'I build blazing-fast, scalable web applications with React, Next.js, and Node.js. With 7+ years of experience, I specialize in e-commerce platforms, SaaS products, and AI-powered applications.',
    hourly_rate: 95,
    experience_level: ExperienceLevel.Expert,
    availability: Availability.Available,
    location: 'San Francisco, CA',
    profile_completion_score: 94,
    rating: 4.9,
    created_at: '2023-11-20T00:00:00Z',
    updated_at: '2024-04-17T00:00:00Z',
  },
  {
    id: 'fp_3',
    user_id: 'u_freelancer_2',
    title: 'UI/UX Designer & Motion Expert',
    bio: 'Award-winning UI/UX designer with a passion for creating beautiful, user-centric digital experiences. I combine strategic thinking with exceptional visual design.',
    hourly_rate: 80,
    experience_level: ExperienceLevel.Expert,
    availability: Availability.Busy,
    location: 'New York, NY',
    profile_completion_score: 98,
    rating: 5.0,
    created_at: '2023-09-05T00:00:00Z',
    updated_at: '2024-04-16T00:00:00Z',
  },
  {
    id: 'fp_4',
    user_id: 'u_freelancer_3',
    title: 'Data Scientist & ML Engineer',
    bio: 'Machine learning specialist with expertise in NLP, computer vision, and predictive analytics. I transform raw data into actionable insights.',
    hourly_rate: 110,
    experience_level: ExperienceLevel.Intermediate,
    availability: Availability.Available,
    location: 'Austin, TX',
    profile_completion_score: 76,
    rating: 4.7,
    created_at: '2024-02-14T00:00:00Z',
    updated_at: '2024-04-14T00:00:00Z',
  },
];

export const SEED_CLIENT_PROFILES: ClientProfileType[] = [
  {
    id: 'cp_1',
    user_id: 'demo_client_001',
    company_name: 'Demo Company',
    company_website: 'https://democompany.com',
    company_size: CompanySize.Small,
    industry: 'Technology',
    company_description: 'We are a demo company for testing purposes',
    location: 'San Francisco, CA',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-04-17T00:00:00Z',
  },
  {
    id: 'cp_2',
    user_id: 'u_client_1',
    company_name: 'TechCorp Innovations',
    company_website: 'https://techcorp.io',
    company_size: CompanySize.Medium,
    industry: 'Technology / SaaS',
    company_description: 'We are a fast-growing SaaS startup building the next generation of enterprise tools.',
    location: 'San Francisco, CA',
    created_at: '2024-01-15T00:00:00Z',
    updated_at: '2024-04-15T00:00:00Z',
  },
  {
    id: 'cp_3',
    user_id: 'u_client_2',
    company_name: 'StartupXYZ',
    company_website: 'https://startupxyz.com',
    company_size: CompanySize.Small,
    industry: 'Fintech',
    company_description: 'Building the future of fintech. We move fast and ship often.',
    location: 'New York, NY',
    created_at: '2024-03-08T00:00:00Z',
    updated_at: '2024-04-16T00:00:00Z',
  },
];

// ─── Jobs ───────────────────────────────────────
export const SEED_JOBS: Job[] = [
  {
    id: 'job_1',
    clientId: 'u_client_1',
    title: 'Senior React Developer for E-commerce Platform',
    description: 'We are looking for an experienced React developer to build a high-performance e-commerce platform. The ideal candidate has strong experience with Next.js, TypeScript, and integrating payment gateways. You will be responsible for the frontend architecture, performance optimization, and working closely with our design team.\n\nKey responsibilities:\n- Build scalable React/Next.js frontend\n- Integrate Stripe and PayPal payment flows\n- Implement real-time inventory updates\n- Optimize for Core Web Vitals\n- Write comprehensive unit and integration tests',
    category: 'Web Development',
    skills: ['React', 'TypeScript', 'Next.js', 'GraphQL', 'Stripe'],
    budgetMin: 5000,
    budgetMax: 8000,
    jobType: 'fixed',
    experienceLevel: 'expert',
    deadline: '2026-05-15',
    status: 'open',
    proposalCount: 14,
    viewCount: 342,
    aiMatchScore: 94,
    isAiRecommended: true,
    postedAt: '2026-04-01',
    isRemote: true,
    gigcoin_cost: 50,
  },
  {
    id: 'job_2',
    clientId: 'u_client_2',
    title: 'UI/UX Designer for Fintech Mobile App',
    description: 'Looking for a talented UI/UX designer to redesign our fintech mobile app. The project involves creating a comprehensive design system, improving user flows, and designing a beautiful, intuitive interface that builds user trust.\n\nDeliverables:\n- Complete design system in Figma\n- 50+ screen designs (iOS and Android)\n- Interactive prototype\n- Design handoff documentation',
    category: 'Design',
    skills: ['Figma', 'UI/UX Design', 'Mobile Design', 'Prototyping', 'Design Systems'],
    budgetMin: 3000,
    budgetMax: 5000,
    jobType: 'fixed',
    experienceLevel: 'intermediate',
    deadline: '2026-05-30',
    status: 'open',
    proposalCount: 8,
    viewCount: 210,
    aiMatchScore: 88,
    isAiRecommended: true,
    postedAt: '2026-04-03',
    isRemote: true,
    gigcoin_cost: 35,
  },
  {
    id: 'job_3',
    clientId: 'u_client_1',
    title: 'Machine Learning Engineer for Recommendation System',
    description: 'We need an ML engineer to build a product recommendation engine for our e-commerce platform. The system should leverage collaborative filtering and deep learning to deliver personalized recommendations.',
    category: 'Data Science',
    skills: ['Python', 'Machine Learning', 'TensorFlow', 'AWS', 'Docker'],
    budgetMin: 6000,
    budgetMax: 10000,
    jobType: 'fixed',
    experienceLevel: 'expert',
    deadline: '2026-06-01',
    status: 'open',
    proposalCount: 5,
    viewCount: 178,
    aiMatchScore: 79,
    isAiRecommended: false,
    postedAt: '2026-04-05',
    isRemote: true,
    gigcoin_cost: 60,
  },
  {
    id: 'job_4',
    clientId: 'u_client_2',
    title: 'Full-Stack Developer for SaaS Dashboard',
    description: 'Building a real-time analytics dashboard for our B2B SaaS product. Need someone comfortable with React, Node.js, WebSockets, and data visualization libraries.',
    category: 'Web Development',
    skills: ['React', 'Node.js', 'WebSocket', 'PostgreSQL', 'D3.js'],
    budgetMin: 100,
    budgetMax: 150,
    jobType: 'hourly',
    experienceLevel: 'intermediate',
    status: 'open',
    proposalCount: 22,
    viewCount: 495,
    aiMatchScore: 91,
    isAiRecommended: true,
    postedAt: '2026-04-06',
    isRemote: true,
    gigcoin_cost: 40,
  },
  {
    id: 'job_5',
    clientId: 'u_client_1',
    title: 'DevOps Engineer – Kubernetes & CI/CD Pipeline',
    description: 'Set up and maintain our cloud infrastructure on AWS EKS. Implement blue-green deployments, monitoring with Prometheus/Grafana, and automated CI/CD pipelines.',
    category: 'DevOps',
    skills: ['Kubernetes', 'AWS', 'Docker', 'Terraform', 'CI/CD', 'Prometheus'],
    budgetMin: 4000,
    budgetMax: 7000,
    jobType: 'fixed',
    experienceLevel: 'expert',
    status: 'open',
    proposalCount: 6,
    viewCount: 134,
    aiMatchScore: 65,
    isAiRecommended: false,
    postedAt: '2026-04-07',
    isRemote: true,
    gigcoin_cost: 55,
  },
  {
    id: 'job_6',
    clientId: 'u_client_2',
    title: 'Content Writer – Technical Blog & Documentation',
    description: 'We need a skilled technical writer to create blog posts, tutorials, and API documentation for our developer tools platform.',
    category: 'Writing',
    skills: ['Technical Writing', 'Markdown', 'API Documentation', 'SEO'],
    budgetMin: 50,
    budgetMax: 80,
    jobType: 'hourly',
    experienceLevel: 'intermediate',
    status: 'open',
    proposalCount: 31,
    viewCount: 612,
    aiMatchScore: 45,
    isAiRecommended: false,
    postedAt: '2026-04-07',
    isRemote: true,
    gigcoin_cost: 25,
  },
];

// ─── Proposals ──────────────────────────────────
export const SEED_PROPOSALS: Proposal[] = [
  {
    id: 'prop_1',
    jobId: 'job_1',
    freelancerId: 'u_freelancer_1',
    clientId: 'u_client_1',
    coverLetter: 'Hi Jordan, I am very excited about this opportunity. I have 7+ years of experience building e-commerce platforms with React and Next.js. I recently delivered a similar project for a Fortune 500 retailer, achieving a 40% increase in conversion rates through performance optimization...',
    bidAmount: 6500,
    deliveryDays: 30,
    status: 'shortlisted',
    aiScore: 96,
    aiSummary: 'Exceptional match. Candidate has directly relevant e-commerce experience with React/Next.js. Portfolio demonstrates strong technical capability and communication.',
    submittedAt: '2026-04-02T10:30:00Z',
    milestones: [
      { id: 'm1', title: 'Architecture & Setup', description: 'Project setup, architecture decisions, basic structure', amount: 1500, dueDate: '2026-04-15', status: 'approved' },
      { id: 'm2', title: 'Core Frontend', description: 'Product listing, cart, checkout UI', amount: 2500, dueDate: '2026-05-01', status: 'in_progress' },
      { id: 'm3', title: 'Payment Integration', description: 'Stripe + PayPal integration and testing', amount: 1500, dueDate: '2026-05-10', status: 'pending' },
      { id: 'm4', title: 'Testing & Deploy', description: 'Test suite and production deployment', amount: 1000, dueDate: '2026-05-15', status: 'pending' },
    ],
  },
  {
    id: 'prop_2',
    jobId: 'job_1',
    freelancerId: 'u_freelancer_3',
    clientId: 'u_client_1',
    coverLetter: 'I have been building React applications for 4 years and would love to work on your e-commerce platform...',
    bidAmount: 5200,
    deliveryDays: 45,
    status: 'pending',
    aiScore: 71,
    aiSummary: 'Good technical fit. Limited e-commerce portfolio but solid React skills. May need guidance on payment integrations.',
    submittedAt: '2026-04-03T14:20:00Z',
  },
  {
    id: 'prop_3',
    jobId: 'job_2',
    freelancerId: 'u_freelancer_2',
    clientId: 'u_client_2',
    coverLetter: 'As an award-winning UI/UX designer specializing in fintech, I am the perfect fit for your app redesign...',
    bidAmount: 4800,
    deliveryDays: 25,
    status: 'accepted',
    aiScore: 98,
    aiSummary: 'Perfect match. Designer has extensive fintech portfolio with measurable results. Design system expertise is exactly what the project needs.',
    submittedAt: '2026-04-04T09:15:00Z',
  },
];

// ─── Projects ────────────────────────────────────
export const SEED_PROJECTS: Project[] = [
  {
    id: 'proj_1',
    jobId: 'job_1',
    clientId: 'u_client_1',
    freelancerId: 'u_freelancer_1',
    title: 'E-commerce Platform Build',
    description: 'Full-stack e-commerce platform with React, Next.js, and Stripe integration.',
    totalBudget: 6500,
    paidAmount: 1500,
    status: 'active',
    startDate: '2026-04-02',
    conversationId: 'conv_1',
    progress: 35,
    milestones: [
      { id: 'm1', title: 'Architecture & Setup', description: 'Project setup and architecture', amount: 1500, dueDate: '2026-04-15', status: 'paid', completedAt: '2026-04-13' },
      { id: 'm2', title: 'Core Frontend', description: 'Product listing, cart, checkout', amount: 2500, dueDate: '2026-05-01', status: 'in_progress' },
      { id: 'm3', title: 'Payment Integration', description: 'Stripe + PayPal', amount: 1500, dueDate: '2026-05-10', status: 'pending' },
      { id: 'm4', title: 'Testing & Deploy', description: 'Test suite and deployment', amount: 1000, dueDate: '2026-05-15', status: 'pending' },
    ],
  },
];

// ─── Messages ─────────────────────────────────────
export const SEED_MESSAGES: Message[] = [
  { id: 'msg_1', conversationId: 'conv_1', senderId: 'u_client_1', content: 'Hi Alex! Looking forward to working together on this project.', type: 'text', createdAt: '2026-04-02T11:00:00Z', isRead: true },
  { id: 'msg_2', conversationId: 'conv_1', senderId: 'u_freelancer_1', content: 'Hi Jordan! Likewise. I have reviewed the requirements and I\'m ready to start. Should we have a quick call to align on the tech stack?', type: 'text', createdAt: '2026-04-02T11:15:00Z', isRead: true },
  { id: 'msg_3', conversationId: 'conv_1', senderId: 'u_client_1', content: 'Sure! I\'ll send a calendar invite for tomorrow at 2pm PST.', type: 'text', createdAt: '2026-04-02T11:20:00Z', isRead: true },
  { id: 'msg_4', conversationId: 'conv_1', senderId: 'u_freelancer_1', content: 'Perfect. In the meantime, I\'ve started on the project architecture diagram.', type: 'text', createdAt: '2026-04-02T11:25:00Z', isRead: true },
  { id: 'msg_5', conversationId: 'conv_1', senderId: 'u_freelancer_1', content: 'architecture-diagram.pdf', type: 'file', fileUrl: '/files/arch.pdf', fileName: 'architecture-diagram.pdf', createdAt: '2026-04-02T11:26:00Z', isRead: true },
  { id: 'msg_6', conversationId: 'conv_1', senderId: 'u_client_1', content: 'This looks great! The component hierarchy makes sense. Approved!', type: 'text', createdAt: '2026-04-03T09:00:00Z', isRead: true },
  { id: 'msg_7', conversationId: 'conv_1', senderId: 'u_freelancer_1', content: 'Just completed the milestone 1 - Architecture & Setup. The Next.js project is bootstrapped with TypeScript, ESLint, Prettier, and Husky pre-commit hooks. CI/CD pipeline is configured on GitHub Actions. Ready for review!', type: 'text', createdAt: '2026-04-13T16:30:00Z', isRead: true },
  { id: 'msg_8', conversationId: 'conv_1', senderId: 'u_client_1', content: 'Excellent work! Milestone approved. Working on payment for this milestone now.', type: 'text', createdAt: '2026-04-13T17:00:00Z', isRead: false },
];

// ─── Notifications ────────────────────────────────
export const SEED_NOTIFICATIONS: Notification[] = [
  { id: 'notif_1', userId: 'u_client_1', type: 'proposal', title: 'New Proposal Received', body: 'Alex Johnson submitted a proposal for "Senior React Developer for E-commerce Platform"', isRead: false, createdAt: '2026-04-02T10:30:00Z', actionUrl: '/proposals' },
  { id: 'notif_2', userId: 'u_client_1', type: 'ai_suggestion', title: '🤖 AI Match Found', body: 'Our AI found 3 highly-qualified freelancers for your React developer role. Match scores: 96%, 88%, 82%', isRead: false, createdAt: '2026-04-02T11:00:00Z', actionUrl: '/proposals' },
  { id: 'notif_3', userId: 'u_freelancer_1', type: 'job_match', title: '⚡ High Match Job', body: 'New job posted: "Senior React Developer for E-commerce Platform" – 94% match score!', isRead: true, createdAt: '2026-04-01T08:00:00Z', actionUrl: '/jobs/job_1' },
  { id: 'notif_4', userId: 'u_freelancer_1', type: 'message', title: 'New Message from Jordan', body: 'Excellent work! Milestone approved. Working on payment...', isRead: false, createdAt: '2026-04-13T17:00:00Z', actionUrl: '/workspace/proj_1' },
  { id: 'notif_5', userId: 'u_freelancer_1', type: 'payment', title: '💰 Payment Received', body: 'You received $1,500 for milestone "Architecture & Setup" in project E-commerce Platform Build', isRead: false, createdAt: '2026-04-14T10:00:00Z', actionUrl: '/workspace/proj_1' },
  { id: 'notif_6', userId: 'u_client_1', type: 'milestone', title: 'Milestone Submitted', body: 'Alex Johnson submitted Milestone 2: Core Frontend for review', isRead: false, createdAt: '2026-04-20T14:00:00Z', actionUrl: '/workspace/proj_1' },
];

// ─── Reviews ─────────────────────────────────────
export const SEED_REVIEWS: Review[] = [
  { id: 'rev_1', jobId: 'job_old_1', reviewerId: 'u_client_old_1', revieweeId: 'u_freelancer_1', rating: 5, comment: 'Alex is an absolute rockstar. Delivered ahead of schedule with exceptional quality. Highly recommended!', createdAt: '2026-02-15', skills: [{ name: 'React', rating: 5 }, { name: 'TypeScript', rating: 5 }, { name: 'Communication', rating: 5 }] },
  { id: 'rev_2', jobId: 'job_old_2', reviewerId: 'u_client_old_2', revieweeId: 'u_freelancer_1', rating: 5, comment: 'Outstanding work on our SaaS platform. Alex\'s attention to detail and proactive communication made this project a great experience.', createdAt: '2026-01-20' },
  { id: 'rev_3', jobId: 'job_old_3', reviewerId: 'u_client_old_3', revieweeId: 'u_freelancer_1', rating: 4, comment: 'Great developer, solid code quality. Would hire again.', createdAt: '2025-12-10' },
  { id: 'rev_4', jobId: 'job_old_4', reviewerId: 'u_client_old_4', revieweeId: 'u_freelancer_2', rating: 5, comment: 'Sarah is the best designer I have ever worked with. Her work transformed our app and directly contributed to a 40% increase in user engagement.', createdAt: '2026-03-01' },
  { id: 'rev_5', jobId: 'job_old_5', reviewerId: 'u_client_old_5', revieweeId: 'u_freelancer_2', rating: 5, comment: 'The design system Sarah created is absolutely stunning. Professional, fast, and deeply talented.', createdAt: '2026-01-15' },
  { id: 'rev_6', jobId: 'job_1', reviewerId: 'u_client_1', revieweeId: 'u_freelancer_1', rating: 2, comment: 'Delivery was late and the quality was not what I expected. Communication was poor and I had to follow up multiple times.', createdAt: '2026-04-10' },
  { id: 'rev_7', jobId: 'job_2', reviewerId: 'u_client_2', revieweeId: 'u_freelancer_2', rating: 1, comment: 'This is spam! Click here for discount offers!!!', createdAt: '2026-04-12' },
  { id: 'rev_8', jobId: 'job_3', reviewerId: 'u_client_1', revieweeId: 'u_freelancer_3', rating: 3, comment: 'Average work. Met the basic requirements but nothing exceptional. Could have been better with more attention to detail.', createdAt: '2026-04-08' },
  { id: 'rev_9', jobId: 'job_4', reviewerId: 'u_client_2', revieweeId: 'u_freelancer_1', rating: 4, comment: 'Good experience overall. The freelancer was responsive and delivered quality work. A few minor issues but nothing major.', createdAt: '2026-03-28' },
  { id: 'rev_10', jobId: 'job_5', reviewerId: 'u_client_1', revieweeId: 'u_freelancer_2', rating: 2, comment: 'Not satisfied. The work had several bugs and required extensive revisions. Would not recommend.', createdAt: '2026-03-25' },
  { id: 'rev_11', jobId: 'job_6', reviewerId: 'demo_client_001', revieweeId: 'u_freelancer_1', rating: 5, comment: 'Excellent work! Very professional and exceeded my expectations. Will definitely work with this freelancer again.', createdAt: '2026-04-15' },
  { id: 'rev_12', jobId: 'job_7', reviewerId: 'u_client_2', revieweeId: 'u_freelancer_3', rating: 4, comment: 'Solid work and good communication. Delivered on time and met all requirements. Would hire again.', createdAt: '2026-04-05' },
  { id: 'rev_13', jobId: 'job_8', reviewerId: 'u_client_1', revieweeId: 'u_freelancer_2', rating: 1, comment: 'Terrible experience!!!! Never hire this person!!!', createdAt: '2026-04-01' },
  { id: 'rev_14', jobId: 'job_9', reviewerId: 'demo_client_001', revieweeId: 'u_freelancer_3', rating: 3, comment: 'The work was okay but there were some communication issues. Had to clarify requirements multiple times.', createdAt: '2026-03-20' },
  { id: 'rev_15', jobId: 'job_10', reviewerId: 'u_client_2', revieweeId: 'u_freelancer_1', rating: 5, comment: 'Amazing freelancer! Highly skilled, great communication, and delivered exceptional results. Best experience on this platform!', createdAt: '2026-04-18' },
];

// ─── Market Insights Data ─────────────────────────
export const MARKET_INSIGHTS = {
  averageRatesBySkill: [
    { id: 'skill-aiml', skill: 'AI/ML', rate: 125, demand: 95 },
    { id: 'skill-blockchain', skill: 'Blockchain', rate: 115, demand: 72 },
    { id: 'skill-react', skill: 'React/Next.js', rate: 95, demand: 88 },
    { id: 'skill-flutter', skill: 'Flutter', rate: 85, demand: 80 },
    { id: 'skill-uiux', skill: 'UI/UX Design', rate: 82, demand: 76 },
    { id: 'skill-nodejs', skill: 'Node.js', rate: 90, demand: 84 },
    { id: 'skill-python', skill: 'Python', rate: 100, demand: 91 },
    { id: 'skill-devops', skill: 'DevOps/K8s', rate: 110, demand: 78 },
  ],
  monthlyEarnings: [
    { id: 'market-oct', month: 'Oct', freelancer: 3200, client: 12000 },
    { id: 'market-nov', month: 'Nov', freelancer: 4100, client: 15000 },
    { id: 'market-dec', month: 'Dec', freelancer: 3800, client: 11000 },
    { id: 'market-jan', month: 'Jan', freelancer: 5200, client: 18000 },
    { id: 'market-feb', month: 'Feb', freelancer: 6100, client: 22000 },
    { id: 'market-mar', month: 'Mar', freelancer: 7400, client: 28000 },
    { id: 'market-apr', month: 'Apr', freelancer: 8200, client: 31000 },
  ],
  trendingCategories: [
    { name: 'AI & Machine Learning', growth: '+142%', jobs: 3842, icon: '🤖' },
    { name: 'Web3 & Blockchain', growth: '+89%', jobs: 1254, icon: '⛓️' },
    { name: 'React Development', growth: '+45%', jobs: 8921, icon: '⚛️' },
    { name: 'UI/UX Design', growth: '+38%', jobs: 6543, icon: '🎨' },
    { name: 'Data Science', growth: '+67%', jobs: 4210, icon: '📊' },
    { name: 'DevOps', growth: '+52%', jobs: 2876, icon: '🔧' },
  ],
  platformStats: {
    totalFreelancers: 52847,
    totalClients: 18294,
    totalProjects: 134562,
    totalPaid: 28400000,
    avgProjectValue: 3200,
    successRate: 96.4,
  },
};